### ISSUE TITLE
The lib not working with Arduino 1.0 beta

### ISSUE THREAD

**Issue by edlau** [felis/USB_Host_Shield_2.0#1]
Downloaded the v2.0 of the lib.  Two major issues:
- WProgram.h renamed to Arduino.h

So after changing the references in the v2.0 USB lib, when compiling the demokit 2, I'm getting:
- message.cpp: In function 'void Notify(const char*)':
- message.cpp:26: error: 'BYTE' was not declared in this scope
