### PR TITLE
Added support for Teensy 4.0 and 4.1

### LINKED ISSUE #529: Support for Teensy 4.0
Hello,

the library works fine with Teensy 3.6, but I  want to test with Teensy 4.0.

When I want to check the code in the Arduino IDE, I get the message:
`C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:1231:2: error: #error "Please define board in avrpins.h"`

So I though I just search for "MK66FX1M0" in all files and add "defined(__IMXRT1062__)".

So I have adjusted:
avrpins.h
```
// pointers are 32 bits on ARM
#define pgm_read_pointer(p) pgm_read_dword(p)

#if defined(CORE_TEENSY) && (defined(__MK20DX128__) || defined(__MK20DX256__) || defined(__MK64FX512__) || defined(__MK66FX1M0__) || defined(__IMXRT1062__))

#include "core_pins.h"
#include "avr_emulation.h"
```

```
MAKE_PIN(P0, CORE_PIN0_PORTREG, CORE_PIN0_BIT, CORE_PIN0_CONFIG);
MAKE_PIN(P1, CORE_PIN1_PORTREG, CORE_PIN1_BIT, CORE_PIN1_CONFIG);
MAKE_PIN(P2, CORE_PIN2_PORTREG, CORE_PIN2_BIT, CORE_PIN2_CONFIG);
MAKE_PIN(P3, CORE_PIN3_PORTREG, CORE_PIN3_BIT, CORE_PIN3_CONFIG);
MAKE_PIN(P4, CORE_PIN4_PORTREG, CORE_PIN4_BIT, CORE_PIN4_CONFIG);
MAKE_PIN(P5, CORE_PIN5_PORTREG, CORE_PIN5_BIT, CORE_PIN5_CONFIG);
MAKE_PIN(P6, CORE_PIN6_PORTREG, CORE_PIN6_BIT, CORE_PIN6_CONFIG);
MAKE_PIN(P7, CORE_PIN7_PORTREG, CORE_PIN7_BIT, CORE_PIN7_CONFIG);
MAKE_PIN(P8, CORE_PIN8_PORTREG, CORE_PIN8_BIT, CORE_PIN8_CONFIG);
MAKE_PIN(P9, CORE_PIN9_PORTREG, CORE_PIN9_BIT, CORE_PIN9_CONFIG);
MAKE_PIN(P10, CORE_PIN10_PORTREG, CORE_PIN10_BIT, CORE_PIN10_CONFIG);
MAKE_PIN(P11, CORE_PIN11_PORTREG, CORE_PIN11_BIT, CORE_PIN11_CONFIG);
MAKE_PIN(P12, CORE_PIN12_PORTREG, CORE_PIN12_BIT, CORE_PIN12_CONFIG);
MAKE_PIN(P13, CORE_PIN13_PORTREG, CORE_PIN13_BIT, CORE_PIN13_CONFIG);
MAKE_PIN(P14, CORE_PIN14_PORTREG, CORE_PIN14_BIT, CORE_PIN14_CONFIG);
MAKE_PIN(P15, CORE_PIN15_PORTREG, CORE_PIN15_BIT, CORE_PIN15_CONFIG);
MAKE_PIN(P16, CORE_PIN16_PORTREG, CORE_PIN16_BIT, CORE_PIN16_CONFIG);
MAKE_PIN(P17, CORE_PIN17_PORTREG, CORE_PIN17_BIT, CORE_PIN17_CONFIG);
MAKE_PIN(P18, CORE_PIN18_PORTREG, CORE_PIN18_BIT, CORE_PIN18_CONFIG);
MAKE_PIN(P19, CORE_PIN19_PORTREG, CORE_PIN19_BIT, CORE_PIN19_CONFIG);
MAKE_PIN(P20, CORE_PIN20_PORTREG, CORE_PIN20_BIT, CORE_PIN20_CONFIG);
MAKE_PIN(P21, CORE_PIN21_PORTREG, CORE_PIN21_BIT, CORE_PIN21_CONFIG);
MAKE_PIN(P22, CORE_PIN22_PORTREG, CORE_PIN22_BIT, CORE_PIN22_CONFIG);
MAKE_PIN(P23, CORE_PIN23_PORTREG, CORE_PIN23_BIT, CORE_PIN23_CONFIG);
MAKE_PIN(P24, CORE_PIN24_PORTREG, CORE_PIN24_BIT, CORE_PIN24_CONFIG);
MAKE_PIN(P25, CORE_PIN25_PORTREG, CORE_PIN25_BIT, CORE_PIN25_CONFIG);
MAKE_PIN(P26, CORE_PIN26_PORTREG, CORE_PIN26_BIT, CORE_PIN26_CONFIG);
MAKE_PIN(P27, CORE_PIN27_PORTREG, CORE_PIN27_BIT, CORE_PIN27_CONFIG);
MAKE_PIN(P28, CORE_PIN28_PORTREG, CORE_PIN28_BIT, CORE_PIN28_CONFIG);
MAKE_PIN(P29, CORE_PIN29_PORTREG, CORE_PIN29_BIT, CORE_PIN29_CONFIG);
MAKE_PIN(P30, CORE_PIN30_PORTREG, CORE_PIN30_BIT, CORE_PIN30_CONFIG);
MAKE_PIN(P31, CORE_PIN31_PORTREG, CORE_PIN31_BIT, CORE_PIN31_CONFIG);
MAKE_PIN(P32, CORE_PIN32_PORTREG, CORE_PIN32_BIT, CORE_PIN32_CONFIG);
MAKE_PIN(P33, CORE_PIN33_PORTREG, CORE_PIN33_BIT, CORE_PIN33_CONFIG);
#if defined(__MK64FX512__) || defined(__MK66FX1M0__)
MAKE_PIN(P34, CORE_PIN34_PORTREG, CORE_PIN34_BIT, CORE_PIN34_CONFIG);
MAKE_PIN(P35, CORE_PIN35_PORTREG, CORE_PIN35_BIT, CORE_PIN35_CONFIG);
MAKE_PIN(P36, CORE_PIN36_PORTREG, CORE_PIN36_BIT, CORE_PIN36_CONFIG);
MAKE_PIN(P37, CORE_PIN37_PORTREG, CORE_PIN37_BIT, CORE_PIN37_CONFIG);
MAKE_PIN(P38, CORE_PIN38_PORTREG, CORE_PIN38_BIT, CORE_PIN38_CONFIG);
MAKE_PIN(P39, CORE_PIN39_PORTREG, CORE_PIN39_BIT, CORE_PIN39_CONFIG);
MAKE_PIN(P40, CORE_PIN40_PORTREG, CORE_PIN40_BIT, CORE_PIN40_CONFIG);
MAKE_PIN(P41, CORE_PIN41_PORTREG, CORE_PIN41_BIT, CORE_PIN41_CONFIG);
MAKE_PIN(P42, CORE_PIN42_PORTREG, CORE_PIN42_BIT, CORE_PIN42_CONFIG);
MAKE_PIN(P43, CORE_PIN43_PORTREG, CORE_PIN43_BIT, CORE_PIN43_CONFIG);
MAKE_PIN(P44, CORE_PIN44_PORTREG, CORE_PIN44_BIT, CORE_PIN44_CONFIG);
MAKE_PIN(P45, CORE_PIN45_PORTREG, CORE_PIN45_BIT, CORE_PIN45_CONFIG);
MAKE_PIN(P46, CORE_PIN46_PORTREG, CORE_PIN46_BIT, CORE_PIN46_CONFIG);
MAKE_PIN(P47, CORE_PIN47_PORTREG, CORE_PIN47_BIT, CORE_PIN47_CONFIG);
MAKE_PIN(P48, CORE_PIN48_PORTREG, CORE_PIN48_BIT, CORE_PIN48_CONFIG);
MAKE_PIN(P49, CORE_PIN49_PORTREG, CORE_PIN49_BIT, CORE_PIN49_CONFIG);
MAKE_PIN(P50, CORE_PIN50_PORTREG, CORE_PIN50_BIT, CORE_PIN50_CONFIG);
MAKE_PIN(P51, CORE_PIN51_PORTREG, CORE_PIN51_BIT, CORE_PIN51_CONFIG);
MAKE_PIN(P52, CORE_PIN52_PORTREG, CORE_PIN52_BIT, CORE_PIN52_CONFIG);
MAKE_PIN(P53, CORE_PIN53_PORTREG, CORE_PIN53_BIT, CORE_PIN53_CONFIG);
MAKE_PIN(P54, CORE_PIN54_PORTREG, CORE_PIN54_BIT, CORE_PIN54_CONFIG);
MAKE_PIN(P55, CORE_PIN55_PORTREG, CORE_PIN55_BIT, CORE_PIN55_CONFIG);
MAKE_PIN(P56, CORE_PIN56_PORTREG, CORE_PIN56_BIT, CORE_PIN56_CONFIG);
MAKE_PIN(P57, CORE_PIN57_PORTREG, CORE_PIN57_BIT, CORE_PIN57_CONFIG);
MAKE_PIN(P58, CORE_PIN58_PORTREG, CORE_PIN58_BIT, CORE_PIN58_CONFIG);
MAKE_PIN(P59, CORE_PIN59_PORTREG, CORE_PIN59_BIT, CORE_PIN59_CONFIG);
MAKE_PIN(P60, CORE_PIN60_PORTREG, CORE_PIN60_BIT, CORE_PIN60_CONFIG);
MAKE_PIN(P61, CORE_PIN61_PORTREG, CORE_PIN61_BIT, CORE_PIN61_CONFIG);
MAKE_PIN(P62, CORE_PIN62_PORTREG, CORE_PIN62_BIT, CORE_PIN62_CONFIG);
MAKE_PIN(P63, CORE_PIN63_PORTREG, CORE_PIN63_BIT, CORE_PIN63_CONFIG);
#endif


#if defined(__IMXRT1062__)
MAKE_PIN(P34, CORE_PIN34_PORTREG, CORE_PIN34_BIT, CORE_PIN34_CONFIG);
MAKE_PIN(P35, CORE_PIN35_PORTREG, CORE_PIN35_BIT, CORE_PIN35_CONFIG);
MAKE_PIN(P36, CORE_PIN36_PORTREG, CORE_PIN36_BIT, CORE_PIN36_CONFIG);
MAKE_PIN(P37, CORE_PIN37_PORTREG, CORE_PIN37_BIT, CORE_PIN37_CONFIG);
MAKE_PIN(P38, CORE_PIN38_PORTREG, CORE_PIN38_BIT, CORE_PIN38_CONFIG);
MAKE_PIN(P39, CORE_PIN39_PORTREG, CORE_PIN39_BIT, CORE_PIN39_CONFIG);
#endif

```

usbhost.h:

```
#elif (defined(CORE_TEENSY) && (defined(__MK20DX128__) || defined(__MK20DX256__) || defined(__MK64FX512__) || defined(__MK66FX1M0__) ||defined(__IMXRT1062__)|| defined(__MKL26Z64__))) || defined(__ARDUINO_ARC__) || defined(__ARDUINO_X86__) || defined(__MIPSEL__) || defined(STM32F4)
typedef SPi< P13, P11, P12, P10 > spi;
```

But now I get a lot of those errors here:
```
C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h: In static member function 'static void P0::SetDirRead()':

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:834:17: error: 'PORT_PCR_SRE' was not declared in this scope

     configReg = PORT_PCR_SRE | PORT_PCR_DSE | PORT_PCR_MUX(1); \

                 ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:846:1: note: in expansion of macro 'MAKE_PIN'

 MAKE_PIN(P0, CORE_PIN0_PORTREG, CORE_PIN0_BIT, CORE_PIN0_CONFIG);

 ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:834:32: error: 'PORT_PCR_DSE' was not declared in this scope

     configReg = PORT_PCR_SRE | PORT_PCR_DSE | PORT_PCR_MUX(1); \

                                ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:846:1: note: in expansion of macro 'MAKE_PIN'

 MAKE_PIN(P0, CORE_PIN0_PORTREG, CORE_PIN0_BIT, CORE_PIN0_CONFIG);

 ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:834:61: error: 'PORT_PCR_MUX' was not declared in this scope

     configReg = PORT_PCR_SRE | PORT_PCR_DSE | PORT_PCR_MUX(1); \

                                                             ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:846:1: note: in expansion of macro 'MAKE_PIN'

 MAKE_PIN(P0, CORE_PIN0_PORTREG, CORE_PIN0_BIT, CORE_PIN0_CONFIG);

 ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h: In static member function 'static void P0::SetDirWrite()':

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:838:17: error: 'PORT_PCR_SRE' was not declared in this scope

     configReg = PORT_PCR_SRE | PORT_PCR_DSE | PORT_PCR_MUX(1); \

                 ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:846:1: note: in expansion of macro 'MAKE_PIN'

 MAKE_PIN(P0, CORE_PIN0_PORTREG, CORE_PIN0_BIT, CORE_PIN0_CONFIG);

 ^

C:\Program Files (x86)\Arduino\libraries\USB_Host_Shield_2.0-master/avrpins.h:838:32: error: 'PORT_PCR_DSE' was not declared in this scope

     configReg = PORT_PCR_SRE | PORT_PCR_DSE | PORT_PCR_MUX(1); \
```

So I thought it was easy, but now I have no idea what might be the issue or how to correctly add the Teensy 4.0 to the library. Any ideas?

### LINKED ISSUE #560: "Please define board in avrpins.h"   Teeensy 4.0
Hello, i use the Usb-host-shield library alot, very good piece of software, thanks again.
I have a little question about Teensy 4.0. I try to compile the board_qc code for it.
But couse it's new it's not in the avrpins.h file.
Can i do that myself if i ask paul Stoffregen the info, or is that a bit over my head.
I see the board info, so adding the teensy 4.0 info would not be that difficult, or is there much more to come after that and 
is that way of thinking way to simpel. And can you give me advice how to go further, and help me on the way,
maybe there is some support for teensy4 
Thanks in Advance, Dian from the Netherlands

### PR DESCRIPTION
**Pull request by Lauszus**
Fixes #529, fixes #560

### CODE REVIEW

**Comment by Lauszus** [comment]
I've also replaced Travis with Github Actions, as Travis was painfully slow to even start the jobs.

**Comment by unitbob1** [comment]
To confirm, does this enable the use of the Teensy 4.1 natively, using the USB headers found on top of the board, or using the external USB host shield?

**Comment by Lauszus** [comment]
@unitbob1 this is for using the USB host shield only. If you want to use the native interface, then check out this library: https://github.com/PaulStoffregen/USBHost_t36

**Comment by xxxajk** [comment]
...or uhs3, which still needs a tid-bit of work, but should support it just fine.

**Comment by shift838** [comment]
Even with this latest code to add support for Teensy 4.0 and 4.1 I still cannot get this my code compiled.  It compiles under Teensy 3.2 but not 4.0 or 4.1

I get the below error:

#error "Please define board in avrpins.h"

**Comment by xxxajk** [comment]
Native interface is also supported under UHS30

**Comment by shift838** [comment]
would this require code changes or is UHS30 backwards compatible to 2.0 syntax?

**Comment by xxxajk** [comment]
It is mostly compatible. Many things are changed for the better. 
Examples:

You don't have to constantly poll the USB, because it operates in the background once started.

You define in the sketch what you want to use

Interfaces are unified, e.g. USB serial convertors are all treated the same.

...and much more

**Comment by shift838** [comment]
i uninstalled the Arduino IDE and reinstalled.

in 2.0 when I compile for Teensy 3.2 i would use the below include statements:

#include <hidboot.h>
#include <usbhub.h>

Is there any docs to explain the new UHS 3.0 ?

What would replace those include statements.

I have tried 

#include <UHS_HIDRAWBOOT_KEYBOARD.h>
#include <UHS_HUB.h>

but get :

fatal error: UHS_HIDRAWBOOT_KEYBOARD.h: No such file or directory

**Comment by xxxajk** [comment]
You use defines, not includes. See the examples.
